<a href="https://colab.research.google.com/github/zahra-sharifzadeh/Tensoflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


##Scalar

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# dim of tensor
scalar.ndim

0

## Vector

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

##Matrix

In [7]:
matrix = tf.constant([[10, 7],
                     [10, 7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
another_matrix  = tf.constant([
    [10. , 7.],
    [12., 13.],
    [14., 15.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [12., 13.],
       [14., 15.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

##Tensor

In [14]:
tensor = tf.constant([
    [[1, 2],
     [3, 4]],

    [[4, 5],
     [6, 7]]])

tensor,tensor.ndim

(<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[4, 5],
         [6, 7]]], dtype=int32)>,
 3)

## `tf.Variable`

In [15]:
changeable_tensor = tf.Variable([10, 7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [16]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [17]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

###.assign()

In [19]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## Creating random tensor

In [21]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1, random_1.shape

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 TensorShape([3, 2]))